USE DB_MeshUp;

DROP TABLE IF EXISTS Collection_Element;
DROP TABLE IF EXISTS Collection;
DROP TABLE IF EXISTS Search_History;
DROP TABLE IF EXISTS Notification;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Model;
DROP TABLE IF EXISTS Category;

DROP TABLE IF EXISTS `Like`; 
DROP TABLE IF EXISTS User;

CREATE TABLE User (
Email VARCHAR(50) PRIMARY KEY,
Username VARCHAR(30) NOT NULL,
Pass VARCHAR(30) NOT NULL,
Profile_Picture MEDIUMBLOB,
Birthdate DATE
);

CREATE TABLE Category (
CategoryId SMALLINT AUTO_INCREMENT PRIMARY KEY,
Category_Name VARCHAR(30),
Category_Description VARCHAR(100)
);

CREATE TABLE Model(
ModelId SMALLINT AUTO_INCREMENT PRIMARY KEY,
Model LONGBLOB NOT NULL,
Texture MEDIUMBLOB NOT NULL
);

CREATE TABLE Post(
PostId SMALLINT AUTO_INCREMENT PRIMARY KEY,
Post_Name VARCHAR(50) NOT NULL,
Post_Description VARCHAR(250) NOT NULL,
Post_Date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
Post_Status BIT DEFAULT 1,
ModelId SMALLINT,
CategoryId SMALLINT,
Email VARCHAR(50),
FOREIGN KEY (ModelId) REFERENCES Model(ModelId),
FOREIGN KEY (CategoryId) REFERENCES Category(CategoryId),
FOREIGN KEY (Email) REFERENCES User(Email)
);

CREATE TABLE `Like`(
LikeId INT AUTO_INCREMENT PRIMARY KEY,
Email VARCHAR(50),
ThingLikedId SMALLINT NOT NULL,
ThingLiked ENUM("post","comment") NOT NULL,
Status BIT DEFAULT 1,
FOREIGN KEY (Email) REFERENCES User(Email)
);

CREATE TABLE Comment(
CommentId SMALLINT AUTO_INCREMENT PRIMARY KEY,
Review VARCHAR(250) NOT NULL,
Rating TINYINT NOT NULL,
Email VARCHAR(50),
PostId SMALLINT,
FOREIGN KEY (Email) REFERENCES User(Email),
FOREIGN KEY (PostId) REFERENCES Post(PostId)
);

CREATE TABLE Collection(
CollectionId SMALLINT AUTO_INCREMENT PRIMARY KEY,
Collection_Name VARCHAR(50) NOT NULL,
Collection_Status BIT DEFAULT 1,
Email VARCHAR(50),
FOREIGN KEY (Email) REFERENCES User(Email)
);

CREATE TABLE Search_History(
HistoryId SMALLINT AUTO_INCREMENT PRIMARY KEY,
Search VARCHAR(50) NOT NULL,
Search_Date DATETIME,
Search_Status BIT DEFAULT 1,
Email VARCHAR(50),
FOREIGN KEY (Email) REFERENCES User(Email)
);

CREATE TABLE Notification(
NotificationId SMALLINT AUTO_INCREMENT PRIMARY KEY,
Matter VARCHAR(50),
Emitter_Email VARCHAR(50),
PostId SMALLINT,
Status BIT DEFAULT 0,
FOREIGN KEY (Emitter_Email) REFERENCES User(Email),
FOREIGN KEY (PostId) REFERENCES Post(PostId)
);

CREATE TABLE Collection_Element(
ElementId SMALLINT AUTO_INCREMENT PRIMARY KEY,
CollectionId SMALLINT,
PostId SMALLINT,
FOREIGN KEY (CollectionId) REFERENCES Collection(CollectionId),
FOREIGN KEY (PostId) REFERENCES Post(PostId)
);